// This file is part of Vassago.
// See LICENSE-Apache-2.0 for license information.

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.34.1
// source: proto/vassago.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Vassago_Ping_FullMethodName                       = "/vassago.Vassago/Ping"
	Vassago_AddMemory_FullMethodName                  = "/vassago.Vassago/AddMemory"
	Vassago_GetMemory_FullMethodName                  = "/vassago.Vassago/GetMemory"
	Vassago_UpdateMemory_FullMethodName               = "/vassago.Vassago/UpdateMemory"
	Vassago_RemoveMemory_FullMethodName               = "/vassago.Vassago/RemoveMemory"
	Vassago_ListMemories_FullMethodName               = "/vassago.Vassago/ListMemories"
	Vassago_Search_FullMethodName                     = "/vassago.Vassago/Search"
	Vassago_SearchSessions_FullMethodName             = "/vassago.Vassago/SearchSessions"
	Vassago_ListSessions_FullMethodName               = "/vassago.Vassago/ListSessions"
	Vassago_GetHotBlock_FullMethodName                = "/vassago.Vassago/GetHotBlock"
	Vassago_CreateSession_FullMethodName              = "/vassago.Vassago/CreateSession"
	Vassago_AddMessages_FullMethodName                = "/vassago.Vassago/AddMessages"
	Vassago_EndSession_FullMethodName                 = "/vassago.Vassago/EndSession"
	Vassago_GetSession_FullMethodName                 = "/vassago.Vassago/GetSession"
	Vassago_Consolidate_FullMethodName                = "/vassago.Vassago/Consolidate"
	Vassago_GetConsolidationCandidates_FullMethodName = "/vassago.Vassago/GetConsolidationCandidates"
	Vassago_Subscribe_FullMethodName                  = "/vassago.Vassago/Subscribe"
	Vassago_RegisterAgent_FullMethodName              = "/vassago.Vassago/RegisterAgent"
	Vassago_Heartbeat_FullMethodName                  = "/vassago.Vassago/Heartbeat"
	Vassago_ChatStream_FullMethodName                 = "/vassago.Vassago/ChatStream"
	Vassago_AddTodo_FullMethodName                    = "/vassago.Vassago/AddTodo"
	Vassago_ListTodos_FullMethodName                  = "/vassago.Vassago/ListTodos"
	Vassago_CompleteTodo_FullMethodName               = "/vassago.Vassago/CompleteTodo"
	Vassago_RemoveTodo_FullMethodName                 = "/vassago.Vassago/RemoveTodo"
	Vassago_AddSkill_FullMethodName                   = "/vassago.Vassago/AddSkill"
	Vassago_GetSkill_FullMethodName                   = "/vassago.Vassago/GetSkill"
	Vassago_ListSkills_FullMethodName                 = "/vassago.Vassago/ListSkills"
	Vassago_RemoveSkill_FullMethodName                = "/vassago.Vassago/RemoveSkill"
	Vassago_SearchSkills_FullMethodName               = "/vassago.Vassago/SearchSkills"
	Vassago_AddSavedTool_FullMethodName               = "/vassago.Vassago/AddSavedTool"
	Vassago_GetSavedTool_FullMethodName               = "/vassago.Vassago/GetSavedTool"
	Vassago_ListSavedTools_FullMethodName             = "/vassago.Vassago/ListSavedTools"
	Vassago_SearchSavedTools_FullMethodName           = "/vassago.Vassago/SearchSavedTools"
	Vassago_UpdateSavedTool_FullMethodName            = "/vassago.Vassago/UpdateSavedTool"
	Vassago_RemoveSavedTool_FullMethodName            = "/vassago.Vassago/RemoveSavedTool"
	Vassago_SyncChanges_FullMethodName                = "/vassago.Vassago/SyncChanges"
	Vassago_AddTask_FullMethodName                    = "/vassago.Vassago/AddTask"
	Vassago_GetTask_FullMethodName                    = "/vassago.Vassago/GetTask"
	Vassago_ClaimTask_FullMethodName                  = "/vassago.Vassago/ClaimTask"
	Vassago_CompleteTask_FullMethodName               = "/vassago.Vassago/CompleteTask"
	Vassago_FailTask_FullMethodName                   = "/vassago.Vassago/FailTask"
	Vassago_FindReadyTasks_FullMethodName             = "/vassago.Vassago/FindReadyTasks"
	Vassago_ListTasksByStatus_FullMethodName          = "/vassago.Vassago/ListTasksByStatus"
	Vassago_ResetTimedOutTasks_FullMethodName         = "/vassago.Vassago/ResetTimedOutTasks"
	Vassago_DeleteTask_FullMethodName                 = "/vassago.Vassago/DeleteTask"
)

// VassagoClient is the client API for Vassago service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type VassagoClient interface {
	// Health check
	Ping(ctx context.Context, in *HealthCheckRequest, opts ...grpc.CallOption) (*HealthCheckResponse, error)
	// Memory CRUD
	AddMemory(ctx context.Context, in *AddMemoryRequest, opts ...grpc.CallOption) (*AddMemoryResponse, error)
	GetMemory(ctx context.Context, in *GetMemoryRequest, opts ...grpc.CallOption) (*MemoryEntry, error)
	UpdateMemory(ctx context.Context, in *UpdateMemoryRequest, opts ...grpc.CallOption) (*MemoryEntry, error)
	RemoveMemory(ctx context.Context, in *RemoveMemoryRequest, opts ...grpc.CallOption) (*RemoveMemoryResponse, error)
	ListMemories(ctx context.Context, in *ListMemoriesRequest, opts ...grpc.CallOption) (*MemoryList, error)
	// Search
	Search(ctx context.Context, in *SearchRequest, opts ...grpc.CallOption) (*SearchResponse, error)
	SearchSessions(ctx context.Context, in *SearchSessionsRequest, opts ...grpc.CallOption) (*SearchSessionsResponse, error)
	ListSessions(ctx context.Context, in *ListSessionsRequest, opts ...grpc.CallOption) (*ListSessionsResponse, error)
	// Hot block — per-agent computed context
	GetHotBlock(ctx context.Context, in *HotBlockRequest, opts ...grpc.CallOption) (*HotBlockResponse, error)
	// Session lifecycle
	CreateSession(ctx context.Context, in *CreateSessionRequest, opts ...grpc.CallOption) (*Session, error)
	AddMessages(ctx context.Context, in *AddMessagesRequest, opts ...grpc.CallOption) (*Session, error)
	EndSession(ctx context.Context, in *EndSessionRequest, opts ...grpc.CallOption) (*EndSessionResponse, error)
	GetSession(ctx context.Context, in *GetSessionRequest, opts ...grpc.CallOption) (*Session, error)
	// Consolidation
	Consolidate(ctx context.Context, in *ConsolidateRequest, opts ...grpc.CallOption) (*ConsolidateResponse, error)
	GetConsolidationCandidates(ctx context.Context, in *GetConsolidationCandidatesRequest, opts ...grpc.CallOption) (*ConsolidationCandidatesResponse, error)
	// Pub/sub — agent subscribes to memory changes
	Subscribe(ctx context.Context, in *SubscribeRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[UpdateEvent], error)
	// --- Agent Management ---
	RegisterAgent(ctx context.Context, in *RegisterAgentRequest, opts ...grpc.CallOption) (*RegisterAgentResponse, error)
	Heartbeat(ctx context.Context, in *AgentId, opts ...grpc.CallOption) (*Empty, error)
	// --- Chat API ---
	// ChatStream sends a message to an agent session and streams back the
	// response in real-time, including text chunks, tool calls, and status events.
	ChatStream(ctx context.Context, in *ChatRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ChatEvent], error)
	// --- Todo Management ---
	AddTodo(ctx context.Context, in *AddTodoRequest, opts ...grpc.CallOption) (*TodoItem, error)
	ListTodos(ctx context.Context, in *ListTodosRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[TodoItem], error)
	CompleteTodo(ctx context.Context, in *CompleteTodoRequest, opts ...grpc.CallOption) (*TodoItem, error)
	RemoveTodo(ctx context.Context, in *RemoveTodoRequest, opts ...grpc.CallOption) (*Empty, error)
	// --- Skill Management ---
	AddSkill(ctx context.Context, in *AddSkillRequest, opts ...grpc.CallOption) (*SkillEntry, error)
	GetSkill(ctx context.Context, in *GetSkillRequest, opts ...grpc.CallOption) (*SkillEntry, error)
	ListSkills(ctx context.Context, in *ListSkillsRequest, opts ...grpc.CallOption) (*SkillList, error)
	RemoveSkill(ctx context.Context, in *RemoveSkillRequest, opts ...grpc.CallOption) (*RemoveSkillResponse, error)
	SearchSkills(ctx context.Context, in *SearchSkillsRequest, opts ...grpc.CallOption) (*SkillList, error)
	// --- Saved Tool Management ---
	AddSavedTool(ctx context.Context, in *AddSavedToolRequest, opts ...grpc.CallOption) (*SavedToolEntry, error)
	GetSavedTool(ctx context.Context, in *GetSavedToolRequest, opts ...grpc.CallOption) (*SavedToolEntry, error)
	ListSavedTools(ctx context.Context, in *ListSavedToolsRequest, opts ...grpc.CallOption) (*SavedToolList, error)
	SearchSavedTools(ctx context.Context, in *SearchSavedToolsRequest, opts ...grpc.CallOption) (*SavedToolList, error)
	UpdateSavedTool(ctx context.Context, in *UpdateSavedToolRequest, opts ...grpc.CallOption) (*SavedToolEntry, error)
	RemoveSavedTool(ctx context.Context, in *RemoveSavedToolRequest, opts ...grpc.CallOption) (*RemoveSavedToolResponse, error)
	// --- Peer Replication ---
	// SyncChanges returns memory deltas since a given timestamp for a namespace.
	// Peer daemons call this to pull changes during replication.
	SyncChanges(ctx context.Context, in *SyncChangesRequest, opts ...grpc.CallOption) (*SyncChangesResponse, error)
	// --- Task Management (Multi-Agent Orchestration) ---
	AddTask(ctx context.Context, in *AddTaskRequest, opts ...grpc.CallOption) (*TaskEntry, error)
	GetTask(ctx context.Context, in *GetTaskRequest, opts ...grpc.CallOption) (*TaskEntry, error)
	ClaimTask(ctx context.Context, in *ClaimTaskRequest, opts ...grpc.CallOption) (*TaskEntry, error)
	CompleteTask(ctx context.Context, in *CompleteTaskRequest, opts ...grpc.CallOption) (*TaskEntry, error)
	FailTask(ctx context.Context, in *FailTaskRequest, opts ...grpc.CallOption) (*TaskEntry, error)
	FindReadyTasks(ctx context.Context, in *FindReadyTasksRequest, opts ...grpc.CallOption) (*TaskList, error)
	ListTasksByStatus(ctx context.Context, in *ListTasksByStatusRequest, opts ...grpc.CallOption) (*TaskList, error)
	ResetTimedOutTasks(ctx context.Context, in *ResetTimedOutTasksRequest, opts ...grpc.CallOption) (*ResetTimedOutTasksResponse, error)
	DeleteTask(ctx context.Context, in *DeleteTaskRequest, opts ...grpc.CallOption) (*DeleteTaskResponse, error)
}

type vassagoClient struct {
	cc grpc.ClientConnInterface
}

func NewVassagoClient(cc grpc.ClientConnInterface) VassagoClient {
	return &vassagoClient{cc}
}

func (c *vassagoClient) Ping(ctx context.Context, in *HealthCheckRequest, opts ...grpc.CallOption) (*HealthCheckResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HealthCheckResponse)
	err := c.cc.Invoke(ctx, Vassago_Ping_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *vassagoClient) AddMemory(ctx context.Context, in *AddMemoryRequest, opts ...grpc.CallOption) (*AddMemoryResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AddMemoryResponse)
	err := c.cc.Invoke(ctx, Vassago_AddMemory_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *vassagoClient) GetMemory(ctx context.Context, in *GetMemoryRequest, opts ...grpc.CallOption) (*MemoryEntry, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MemoryEntry)
	err := c.cc.Invoke(ctx, Vassago_GetMemory_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *vassagoClient) UpdateMemory(ctx context.Context, in *UpdateMemoryRequest, opts ...grpc.CallOption) (*MemoryEntry, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MemoryEntry)
	err := c.cc.Invoke(ctx, Vassago_UpdateMemory_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *vassagoClient) RemoveMemory(ctx context.Context, in *RemoveMemoryRequest, opts ...grpc.CallOption) (*RemoveMemoryResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RemoveMemoryResponse)
	err := c.cc.Invoke(ctx, Vassago_RemoveMemory_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *vassagoClient) ListMemories(ctx context.Context, in *ListMemoriesRequest, opts ...grpc.CallOption) (*MemoryList, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MemoryList)
	err := c.cc.Invoke(ctx, Vassago_ListMemories_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *vassagoClient) Search(ctx context.Context, in *SearchRequest, opts ...grpc.CallOption) (*SearchResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SearchResponse)
	err := c.cc.Invoke(ctx, Vassago_Search_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *vassagoClient) SearchSessions(ctx context.Context, in *SearchSessionsRequest, opts ...grpc.CallOption) (*SearchSessionsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SearchSessionsResponse)
	err := c.cc.Invoke(ctx, Vassago_SearchSessions_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *vassagoClient) ListSessions(ctx context.Context, in *ListSessionsRequest, opts ...grpc.CallOption) (*ListSessionsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListSessionsResponse)
	err := c.cc.Invoke(ctx, Vassago_ListSessions_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *vassagoClient) GetHotBlock(ctx context.Context, in *HotBlockRequest, opts ...grpc.CallOption) (*HotBlockResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HotBlockResponse)
	err := c.cc.Invoke(ctx, Vassago_GetHotBlock_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *vassagoClient) CreateSession(ctx context.Context, in *CreateSessionRequest, opts ...grpc.CallOption) (*Session, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Session)
	err := c.cc.Invoke(ctx, Vassago_CreateSession_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *vassagoClient) AddMessages(ctx context.Context, in *AddMessagesRequest, opts ...grpc.CallOption) (*Session, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Session)
	err := c.cc.Invoke(ctx, Vassago_AddMessages_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *vassagoClient) EndSession(ctx context.Context, in *EndSessionRequest, opts ...grpc.CallOption) (*EndSessionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EndSessionResponse)
	err := c.cc.Invoke(ctx, Vassago_EndSession_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *vassagoClient) GetSession(ctx context.Context, in *GetSessionRequest, opts ...grpc.CallOption) (*Session, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Session)
	err := c.cc.Invoke(ctx, Vassago_GetSession_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *vassagoClient) Consolidate(ctx context.Context, in *ConsolidateRequest, opts ...grpc.CallOption) (*ConsolidateResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ConsolidateResponse)
	err := c.cc.Invoke(ctx, Vassago_Consolidate_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *vassagoClient) GetConsolidationCandidates(ctx context.Context, in *GetConsolidationCandidatesRequest, opts ...grpc.CallOption) (*ConsolidationCandidatesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ConsolidationCandidatesResponse)
	err := c.cc.Invoke(ctx, Vassago_GetConsolidationCandidates_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *vassagoClient) Subscribe(ctx context.Context, in *SubscribeRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[UpdateEvent], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &Vassago_ServiceDesc.Streams[0], Vassago_Subscribe_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[SubscribeRequest, UpdateEvent]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Vassago_SubscribeClient = grpc.ServerStreamingClient[UpdateEvent]

func (c *vassagoClient) RegisterAgent(ctx context.Context, in *RegisterAgentRequest, opts ...grpc.CallOption) (*RegisterAgentResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RegisterAgentResponse)
	err := c.cc.Invoke(ctx, Vassago_RegisterAgent_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *vassagoClient) Heartbeat(ctx context.Context, in *AgentId, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, Vassago_Heartbeat_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *vassagoClient) ChatStream(ctx context.Context, in *ChatRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ChatEvent], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &Vassago_ServiceDesc.Streams[1], Vassago_ChatStream_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[ChatRequest, ChatEvent]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Vassago_ChatStreamClient = grpc.ServerStreamingClient[ChatEvent]

func (c *vassagoClient) AddTodo(ctx context.Context, in *AddTodoRequest, opts ...grpc.CallOption) (*TodoItem, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TodoItem)
	err := c.cc.Invoke(ctx, Vassago_AddTodo_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *vassagoClient) ListTodos(ctx context.Context, in *ListTodosRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[TodoItem], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &Vassago_ServiceDesc.Streams[2], Vassago_ListTodos_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[ListTodosRequest, TodoItem]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Vassago_ListTodosClient = grpc.ServerStreamingClient[TodoItem]

func (c *vassagoClient) CompleteTodo(ctx context.Context, in *CompleteTodoRequest, opts ...grpc.CallOption) (*TodoItem, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TodoItem)
	err := c.cc.Invoke(ctx, Vassago_CompleteTodo_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *vassagoClient) RemoveTodo(ctx context.Context, in *RemoveTodoRequest, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, Vassago_RemoveTodo_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *vassagoClient) AddSkill(ctx context.Context, in *AddSkillRequest, opts ...grpc.CallOption) (*SkillEntry, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SkillEntry)
	err := c.cc.Invoke(ctx, Vassago_AddSkill_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *vassagoClient) GetSkill(ctx context.Context, in *GetSkillRequest, opts ...grpc.CallOption) (*SkillEntry, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SkillEntry)
	err := c.cc.Invoke(ctx, Vassago_GetSkill_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *vassagoClient) ListSkills(ctx context.Context, in *ListSkillsRequest, opts ...grpc.CallOption) (*SkillList, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SkillList)
	err := c.cc.Invoke(ctx, Vassago_ListSkills_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *vassagoClient) RemoveSkill(ctx context.Context, in *RemoveSkillRequest, opts ...grpc.CallOption) (*RemoveSkillResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RemoveSkillResponse)
	err := c.cc.Invoke(ctx, Vassago_RemoveSkill_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *vassagoClient) SearchSkills(ctx context.Context, in *SearchSkillsRequest, opts ...grpc.CallOption) (*SkillList, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SkillList)
	err := c.cc.Invoke(ctx, Vassago_SearchSkills_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *vassagoClient) AddSavedTool(ctx context.Context, in *AddSavedToolRequest, opts ...grpc.CallOption) (*SavedToolEntry, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SavedToolEntry)
	err := c.cc.Invoke(ctx, Vassago_AddSavedTool_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *vassagoClient) GetSavedTool(ctx context.Context, in *GetSavedToolRequest, opts ...grpc.CallOption) (*SavedToolEntry, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SavedToolEntry)
	err := c.cc.Invoke(ctx, Vassago_GetSavedTool_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *vassagoClient) ListSavedTools(ctx context.Context, in *ListSavedToolsRequest, opts ...grpc.CallOption) (*SavedToolList, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SavedToolList)
	err := c.cc.Invoke(ctx, Vassago_ListSavedTools_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *vassagoClient) SearchSavedTools(ctx context.Context, in *SearchSavedToolsRequest, opts ...grpc.CallOption) (*SavedToolList, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SavedToolList)
	err := c.cc.Invoke(ctx, Vassago_SearchSavedTools_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *vassagoClient) UpdateSavedTool(ctx context.Context, in *UpdateSavedToolRequest, opts ...grpc.CallOption) (*SavedToolEntry, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SavedToolEntry)
	err := c.cc.Invoke(ctx, Vassago_UpdateSavedTool_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *vassagoClient) RemoveSavedTool(ctx context.Context, in *RemoveSavedToolRequest, opts ...grpc.CallOption) (*RemoveSavedToolResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RemoveSavedToolResponse)
	err := c.cc.Invoke(ctx, Vassago_RemoveSavedTool_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *vassagoClient) SyncChanges(ctx context.Context, in *SyncChangesRequest, opts ...grpc.CallOption) (*SyncChangesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SyncChangesResponse)
	err := c.cc.Invoke(ctx, Vassago_SyncChanges_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *vassagoClient) AddTask(ctx context.Context, in *AddTaskRequest, opts ...grpc.CallOption) (*TaskEntry, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TaskEntry)
	err := c.cc.Invoke(ctx, Vassago_AddTask_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *vassagoClient) GetTask(ctx context.Context, in *GetTaskRequest, opts ...grpc.CallOption) (*TaskEntry, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TaskEntry)
	err := c.cc.Invoke(ctx, Vassago_GetTask_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *vassagoClient) ClaimTask(ctx context.Context, in *ClaimTaskRequest, opts ...grpc.CallOption) (*TaskEntry, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TaskEntry)
	err := c.cc.Invoke(ctx, Vassago_ClaimTask_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *vassagoClient) CompleteTask(ctx context.Context, in *CompleteTaskRequest, opts ...grpc.CallOption) (*TaskEntry, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TaskEntry)
	err := c.cc.Invoke(ctx, Vassago_CompleteTask_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *vassagoClient) FailTask(ctx context.Context, in *FailTaskRequest, opts ...grpc.CallOption) (*TaskEntry, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TaskEntry)
	err := c.cc.Invoke(ctx, Vassago_FailTask_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *vassagoClient) FindReadyTasks(ctx context.Context, in *FindReadyTasksRequest, opts ...grpc.CallOption) (*TaskList, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TaskList)
	err := c.cc.Invoke(ctx, Vassago_FindReadyTasks_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *vassagoClient) ListTasksByStatus(ctx context.Context, in *ListTasksByStatusRequest, opts ...grpc.CallOption) (*TaskList, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TaskList)
	err := c.cc.Invoke(ctx, Vassago_ListTasksByStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *vassagoClient) ResetTimedOutTasks(ctx context.Context, in *ResetTimedOutTasksRequest, opts ...grpc.CallOption) (*ResetTimedOutTasksResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ResetTimedOutTasksResponse)
	err := c.cc.Invoke(ctx, Vassago_ResetTimedOutTasks_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *vassagoClient) DeleteTask(ctx context.Context, in *DeleteTaskRequest, opts ...grpc.CallOption) (*DeleteTaskResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteTaskResponse)
	err := c.cc.Invoke(ctx, Vassago_DeleteTask_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// VassagoServer is the server API for Vassago service.
// All implementations must embed UnimplementedVassagoServer
// for forward compatibility.
type VassagoServer interface {
	// Health check
	Ping(context.Context, *HealthCheckRequest) (*HealthCheckResponse, error)
	// Memory CRUD
	AddMemory(context.Context, *AddMemoryRequest) (*AddMemoryResponse, error)
	GetMemory(context.Context, *GetMemoryRequest) (*MemoryEntry, error)
	UpdateMemory(context.Context, *UpdateMemoryRequest) (*MemoryEntry, error)
	RemoveMemory(context.Context, *RemoveMemoryRequest) (*RemoveMemoryResponse, error)
	ListMemories(context.Context, *ListMemoriesRequest) (*MemoryList, error)
	// Search
	Search(context.Context, *SearchRequest) (*SearchResponse, error)
	SearchSessions(context.Context, *SearchSessionsRequest) (*SearchSessionsResponse, error)
	ListSessions(context.Context, *ListSessionsRequest) (*ListSessionsResponse, error)
	// Hot block — per-agent computed context
	GetHotBlock(context.Context, *HotBlockRequest) (*HotBlockResponse, error)
	// Session lifecycle
	CreateSession(context.Context, *CreateSessionRequest) (*Session, error)
	AddMessages(context.Context, *AddMessagesRequest) (*Session, error)
	EndSession(context.Context, *EndSessionRequest) (*EndSessionResponse, error)
	GetSession(context.Context, *GetSessionRequest) (*Session, error)
	// Consolidation
	Consolidate(context.Context, *ConsolidateRequest) (*ConsolidateResponse, error)
	GetConsolidationCandidates(context.Context, *GetConsolidationCandidatesRequest) (*ConsolidationCandidatesResponse, error)
	// Pub/sub — agent subscribes to memory changes
	Subscribe(*SubscribeRequest, grpc.ServerStreamingServer[UpdateEvent]) error
	// --- Agent Management ---
	RegisterAgent(context.Context, *RegisterAgentRequest) (*RegisterAgentResponse, error)
	Heartbeat(context.Context, *AgentId) (*Empty, error)
	// --- Chat API ---
	// ChatStream sends a message to an agent session and streams back the
	// response in real-time, including text chunks, tool calls, and status events.
	ChatStream(*ChatRequest, grpc.ServerStreamingServer[ChatEvent]) error
	// --- Todo Management ---
	AddTodo(context.Context, *AddTodoRequest) (*TodoItem, error)
	ListTodos(*ListTodosRequest, grpc.ServerStreamingServer[TodoItem]) error
	CompleteTodo(context.Context, *CompleteTodoRequest) (*TodoItem, error)
	RemoveTodo(context.Context, *RemoveTodoRequest) (*Empty, error)
	// --- Skill Management ---
	AddSkill(context.Context, *AddSkillRequest) (*SkillEntry, error)
	GetSkill(context.Context, *GetSkillRequest) (*SkillEntry, error)
	ListSkills(context.Context, *ListSkillsRequest) (*SkillList, error)
	RemoveSkill(context.Context, *RemoveSkillRequest) (*RemoveSkillResponse, error)
	SearchSkills(context.Context, *SearchSkillsRequest) (*SkillList, error)
	// --- Saved Tool Management ---
	AddSavedTool(context.Context, *AddSavedToolRequest) (*SavedToolEntry, error)
	GetSavedTool(context.Context, *GetSavedToolRequest) (*SavedToolEntry, error)
	ListSavedTools(context.Context, *ListSavedToolsRequest) (*SavedToolList, error)
	SearchSavedTools(context.Context, *SearchSavedToolsRequest) (*SavedToolList, error)
	UpdateSavedTool(context.Context, *UpdateSavedToolRequest) (*SavedToolEntry, error)
	RemoveSavedTool(context.Context, *RemoveSavedToolRequest) (*RemoveSavedToolResponse, error)
	// --- Peer Replication ---
	// SyncChanges returns memory deltas since a given timestamp for a namespace.
	// Peer daemons call this to pull changes during replication.
	SyncChanges(context.Context, *SyncChangesRequest) (*SyncChangesResponse, error)
	// --- Task Management (Multi-Agent Orchestration) ---
	AddTask(context.Context, *AddTaskRequest) (*TaskEntry, error)
	GetTask(context.Context, *GetTaskRequest) (*TaskEntry, error)
	ClaimTask(context.Context, *ClaimTaskRequest) (*TaskEntry, error)
	CompleteTask(context.Context, *CompleteTaskRequest) (*TaskEntry, error)
	FailTask(context.Context, *FailTaskRequest) (*TaskEntry, error)
	FindReadyTasks(context.Context, *FindReadyTasksRequest) (*TaskList, error)
	ListTasksByStatus(context.Context, *ListTasksByStatusRequest) (*TaskList, error)
	ResetTimedOutTasks(context.Context, *ResetTimedOutTasksRequest) (*ResetTimedOutTasksResponse, error)
	DeleteTask(context.Context, *DeleteTaskRequest) (*DeleteTaskResponse, error)
	mustEmbedUnimplementedVassagoServer()
}

// UnimplementedVassagoServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedVassagoServer struct{}

func (UnimplementedVassagoServer) Ping(context.Context, *HealthCheckRequest) (*HealthCheckResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Ping not implemented")
}
func (UnimplementedVassagoServer) AddMemory(context.Context, *AddMemoryRequest) (*AddMemoryResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method AddMemory not implemented")
}
func (UnimplementedVassagoServer) GetMemory(context.Context, *GetMemoryRequest) (*MemoryEntry, error) {
	return nil, status.Error(codes.Unimplemented, "method GetMemory not implemented")
}
func (UnimplementedVassagoServer) UpdateMemory(context.Context, *UpdateMemoryRequest) (*MemoryEntry, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateMemory not implemented")
}
func (UnimplementedVassagoServer) RemoveMemory(context.Context, *RemoveMemoryRequest) (*RemoveMemoryResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RemoveMemory not implemented")
}
func (UnimplementedVassagoServer) ListMemories(context.Context, *ListMemoriesRequest) (*MemoryList, error) {
	return nil, status.Error(codes.Unimplemented, "method ListMemories not implemented")
}
func (UnimplementedVassagoServer) Search(context.Context, *SearchRequest) (*SearchResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Search not implemented")
}
func (UnimplementedVassagoServer) SearchSessions(context.Context, *SearchSessionsRequest) (*SearchSessionsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SearchSessions not implemented")
}
func (UnimplementedVassagoServer) ListSessions(context.Context, *ListSessionsRequest) (*ListSessionsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListSessions not implemented")
}
func (UnimplementedVassagoServer) GetHotBlock(context.Context, *HotBlockRequest) (*HotBlockResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetHotBlock not implemented")
}
func (UnimplementedVassagoServer) CreateSession(context.Context, *CreateSessionRequest) (*Session, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateSession not implemented")
}
func (UnimplementedVassagoServer) AddMessages(context.Context, *AddMessagesRequest) (*Session, error) {
	return nil, status.Error(codes.Unimplemented, "method AddMessages not implemented")
}
func (UnimplementedVassagoServer) EndSession(context.Context, *EndSessionRequest) (*EndSessionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method EndSession not implemented")
}
func (UnimplementedVassagoServer) GetSession(context.Context, *GetSessionRequest) (*Session, error) {
	return nil, status.Error(codes.Unimplemented, "method GetSession not implemented")
}
func (UnimplementedVassagoServer) Consolidate(context.Context, *ConsolidateRequest) (*ConsolidateResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Consolidate not implemented")
}
func (UnimplementedVassagoServer) GetConsolidationCandidates(context.Context, *GetConsolidationCandidatesRequest) (*ConsolidationCandidatesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetConsolidationCandidates not implemented")
}
func (UnimplementedVassagoServer) Subscribe(*SubscribeRequest, grpc.ServerStreamingServer[UpdateEvent]) error {
	return status.Error(codes.Unimplemented, "method Subscribe not implemented")
}
func (UnimplementedVassagoServer) RegisterAgent(context.Context, *RegisterAgentRequest) (*RegisterAgentResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RegisterAgent not implemented")
}
func (UnimplementedVassagoServer) Heartbeat(context.Context, *AgentId) (*Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method Heartbeat not implemented")
}
func (UnimplementedVassagoServer) ChatStream(*ChatRequest, grpc.ServerStreamingServer[ChatEvent]) error {
	return status.Error(codes.Unimplemented, "method ChatStream not implemented")
}
func (UnimplementedVassagoServer) AddTodo(context.Context, *AddTodoRequest) (*TodoItem, error) {
	return nil, status.Error(codes.Unimplemented, "method AddTodo not implemented")
}
func (UnimplementedVassagoServer) ListTodos(*ListTodosRequest, grpc.ServerStreamingServer[TodoItem]) error {
	return status.Error(codes.Unimplemented, "method ListTodos not implemented")
}
func (UnimplementedVassagoServer) CompleteTodo(context.Context, *CompleteTodoRequest) (*TodoItem, error) {
	return nil, status.Error(codes.Unimplemented, "method CompleteTodo not implemented")
}
func (UnimplementedVassagoServer) RemoveTodo(context.Context, *RemoveTodoRequest) (*Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method RemoveTodo not implemented")
}
func (UnimplementedVassagoServer) AddSkill(context.Context, *AddSkillRequest) (*SkillEntry, error) {
	return nil, status.Error(codes.Unimplemented, "method AddSkill not implemented")
}
func (UnimplementedVassagoServer) GetSkill(context.Context, *GetSkillRequest) (*SkillEntry, error) {
	return nil, status.Error(codes.Unimplemented, "method GetSkill not implemented")
}
func (UnimplementedVassagoServer) ListSkills(context.Context, *ListSkillsRequest) (*SkillList, error) {
	return nil, status.Error(codes.Unimplemented, "method ListSkills not implemented")
}
func (UnimplementedVassagoServer) RemoveSkill(context.Context, *RemoveSkillRequest) (*RemoveSkillResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RemoveSkill not implemented")
}
func (UnimplementedVassagoServer) SearchSkills(context.Context, *SearchSkillsRequest) (*SkillList, error) {
	return nil, status.Error(codes.Unimplemented, "method SearchSkills not implemented")
}
func (UnimplementedVassagoServer) AddSavedTool(context.Context, *AddSavedToolRequest) (*SavedToolEntry, error) {
	return nil, status.Error(codes.Unimplemented, "method AddSavedTool not implemented")
}
func (UnimplementedVassagoServer) GetSavedTool(context.Context, *GetSavedToolRequest) (*SavedToolEntry, error) {
	return nil, status.Error(codes.Unimplemented, "method GetSavedTool not implemented")
}
func (UnimplementedVassagoServer) ListSavedTools(context.Context, *ListSavedToolsRequest) (*SavedToolList, error) {
	return nil, status.Error(codes.Unimplemented, "method ListSavedTools not implemented")
}
func (UnimplementedVassagoServer) SearchSavedTools(context.Context, *SearchSavedToolsRequest) (*SavedToolList, error) {
	return nil, status.Error(codes.Unimplemented, "method SearchSavedTools not implemented")
}
func (UnimplementedVassagoServer) UpdateSavedTool(context.Context, *UpdateSavedToolRequest) (*SavedToolEntry, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateSavedTool not implemented")
}
func (UnimplementedVassagoServer) RemoveSavedTool(context.Context, *RemoveSavedToolRequest) (*RemoveSavedToolResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RemoveSavedTool not implemented")
}
func (UnimplementedVassagoServer) SyncChanges(context.Context, *SyncChangesRequest) (*SyncChangesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SyncChanges not implemented")
}
func (UnimplementedVassagoServer) AddTask(context.Context, *AddTaskRequest) (*TaskEntry, error) {
	return nil, status.Error(codes.Unimplemented, "method AddTask not implemented")
}
func (UnimplementedVassagoServer) GetTask(context.Context, *GetTaskRequest) (*TaskEntry, error) {
	return nil, status.Error(codes.Unimplemented, "method GetTask not implemented")
}
func (UnimplementedVassagoServer) ClaimTask(context.Context, *ClaimTaskRequest) (*TaskEntry, error) {
	return nil, status.Error(codes.Unimplemented, "method ClaimTask not implemented")
}
func (UnimplementedVassagoServer) CompleteTask(context.Context, *CompleteTaskRequest) (*TaskEntry, error) {
	return nil, status.Error(codes.Unimplemented, "method CompleteTask not implemented")
}
func (UnimplementedVassagoServer) FailTask(context.Context, *FailTaskRequest) (*TaskEntry, error) {
	return nil, status.Error(codes.Unimplemented, "method FailTask not implemented")
}
func (UnimplementedVassagoServer) FindReadyTasks(context.Context, *FindReadyTasksRequest) (*TaskList, error) {
	return nil, status.Error(codes.Unimplemented, "method FindReadyTasks not implemented")
}
func (UnimplementedVassagoServer) ListTasksByStatus(context.Context, *ListTasksByStatusRequest) (*TaskList, error) {
	return nil, status.Error(codes.Unimplemented, "method ListTasksByStatus not implemented")
}
func (UnimplementedVassagoServer) ResetTimedOutTasks(context.Context, *ResetTimedOutTasksRequest) (*ResetTimedOutTasksResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ResetTimedOutTasks not implemented")
}
func (UnimplementedVassagoServer) DeleteTask(context.Context, *DeleteTaskRequest) (*DeleteTaskResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteTask not implemented")
}
func (UnimplementedVassagoServer) mustEmbedUnimplementedVassagoServer() {}
func (UnimplementedVassagoServer) testEmbeddedByValue()                 {}

// UnsafeVassagoServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to VassagoServer will
// result in compilation errors.
type UnsafeVassagoServer interface {
	mustEmbedUnimplementedVassagoServer()
}

func RegisterVassagoServer(s grpc.ServiceRegistrar, srv VassagoServer) {
	// If the following call panics, it indicates UnimplementedVassagoServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Vassago_ServiceDesc, srv)
}

func _Vassago_Ping_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HealthCheckRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VassagoServer).Ping(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Vassago_Ping_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VassagoServer).Ping(ctx, req.(*HealthCheckRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Vassago_AddMemory_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddMemoryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VassagoServer).AddMemory(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Vassago_AddMemory_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VassagoServer).AddMemory(ctx, req.(*AddMemoryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Vassago_GetMemory_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetMemoryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VassagoServer).GetMemory(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Vassago_GetMemory_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VassagoServer).GetMemory(ctx, req.(*GetMemoryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Vassago_UpdateMemory_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateMemoryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VassagoServer).UpdateMemory(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Vassago_UpdateMemory_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VassagoServer).UpdateMemory(ctx, req.(*UpdateMemoryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Vassago_RemoveMemory_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RemoveMemoryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VassagoServer).RemoveMemory(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Vassago_RemoveMemory_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VassagoServer).RemoveMemory(ctx, req.(*RemoveMemoryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Vassago_ListMemories_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListMemoriesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VassagoServer).ListMemories(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Vassago_ListMemories_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VassagoServer).ListMemories(ctx, req.(*ListMemoriesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Vassago_Search_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SearchRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VassagoServer).Search(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Vassago_Search_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VassagoServer).Search(ctx, req.(*SearchRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Vassago_SearchSessions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SearchSessionsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VassagoServer).SearchSessions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Vassago_SearchSessions_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VassagoServer).SearchSessions(ctx, req.(*SearchSessionsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Vassago_ListSessions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListSessionsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VassagoServer).ListSessions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Vassago_ListSessions_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VassagoServer).ListSessions(ctx, req.(*ListSessionsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Vassago_GetHotBlock_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HotBlockRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VassagoServer).GetHotBlock(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Vassago_GetHotBlock_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VassagoServer).GetHotBlock(ctx, req.(*HotBlockRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Vassago_CreateSession_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateSessionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VassagoServer).CreateSession(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Vassago_CreateSession_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VassagoServer).CreateSession(ctx, req.(*CreateSessionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Vassago_AddMessages_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddMessagesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VassagoServer).AddMessages(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Vassago_AddMessages_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VassagoServer).AddMessages(ctx, req.(*AddMessagesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Vassago_EndSession_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EndSessionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VassagoServer).EndSession(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Vassago_EndSession_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VassagoServer).EndSession(ctx, req.(*EndSessionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Vassago_GetSession_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetSessionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VassagoServer).GetSession(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Vassago_GetSession_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VassagoServer).GetSession(ctx, req.(*GetSessionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Vassago_Consolidate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ConsolidateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VassagoServer).Consolidate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Vassago_Consolidate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VassagoServer).Consolidate(ctx, req.(*ConsolidateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Vassago_GetConsolidationCandidates_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetConsolidationCandidatesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VassagoServer).GetConsolidationCandidates(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Vassago_GetConsolidationCandidates_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VassagoServer).GetConsolidationCandidates(ctx, req.(*GetConsolidationCandidatesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Vassago_Subscribe_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(SubscribeRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(VassagoServer).Subscribe(m, &grpc.GenericServerStream[SubscribeRequest, UpdateEvent]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Vassago_SubscribeServer = grpc.ServerStreamingServer[UpdateEvent]

func _Vassago_RegisterAgent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterAgentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VassagoServer).RegisterAgent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Vassago_RegisterAgent_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VassagoServer).RegisterAgent(ctx, req.(*RegisterAgentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Vassago_Heartbeat_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AgentId)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VassagoServer).Heartbeat(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Vassago_Heartbeat_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VassagoServer).Heartbeat(ctx, req.(*AgentId))
	}
	return interceptor(ctx, in, info, handler)
}

func _Vassago_ChatStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ChatRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(VassagoServer).ChatStream(m, &grpc.GenericServerStream[ChatRequest, ChatEvent]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Vassago_ChatStreamServer = grpc.ServerStreamingServer[ChatEvent]

func _Vassago_AddTodo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddTodoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VassagoServer).AddTodo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Vassago_AddTodo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VassagoServer).AddTodo(ctx, req.(*AddTodoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Vassago_ListTodos_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ListTodosRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(VassagoServer).ListTodos(m, &grpc.GenericServerStream[ListTodosRequest, TodoItem]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Vassago_ListTodosServer = grpc.ServerStreamingServer[TodoItem]

func _Vassago_CompleteTodo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CompleteTodoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VassagoServer).CompleteTodo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Vassago_CompleteTodo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VassagoServer).CompleteTodo(ctx, req.(*CompleteTodoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Vassago_RemoveTodo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RemoveTodoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VassagoServer).RemoveTodo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Vassago_RemoveTodo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VassagoServer).RemoveTodo(ctx, req.(*RemoveTodoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Vassago_AddSkill_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddSkillRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VassagoServer).AddSkill(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Vassago_AddSkill_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VassagoServer).AddSkill(ctx, req.(*AddSkillRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Vassago_GetSkill_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetSkillRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VassagoServer).GetSkill(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Vassago_GetSkill_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VassagoServer).GetSkill(ctx, req.(*GetSkillRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Vassago_ListSkills_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListSkillsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VassagoServer).ListSkills(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Vassago_ListSkills_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VassagoServer).ListSkills(ctx, req.(*ListSkillsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Vassago_RemoveSkill_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RemoveSkillRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VassagoServer).RemoveSkill(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Vassago_RemoveSkill_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VassagoServer).RemoveSkill(ctx, req.(*RemoveSkillRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Vassago_SearchSkills_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SearchSkillsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VassagoServer).SearchSkills(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Vassago_SearchSkills_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VassagoServer).SearchSkills(ctx, req.(*SearchSkillsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Vassago_AddSavedTool_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddSavedToolRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VassagoServer).AddSavedTool(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Vassago_AddSavedTool_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VassagoServer).AddSavedTool(ctx, req.(*AddSavedToolRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Vassago_GetSavedTool_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetSavedToolRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VassagoServer).GetSavedTool(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Vassago_GetSavedTool_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VassagoServer).GetSavedTool(ctx, req.(*GetSavedToolRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Vassago_ListSavedTools_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListSavedToolsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VassagoServer).ListSavedTools(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Vassago_ListSavedTools_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VassagoServer).ListSavedTools(ctx, req.(*ListSavedToolsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Vassago_SearchSavedTools_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SearchSavedToolsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VassagoServer).SearchSavedTools(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Vassago_SearchSavedTools_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VassagoServer).SearchSavedTools(ctx, req.(*SearchSavedToolsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Vassago_UpdateSavedTool_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateSavedToolRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VassagoServer).UpdateSavedTool(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Vassago_UpdateSavedTool_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VassagoServer).UpdateSavedTool(ctx, req.(*UpdateSavedToolRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Vassago_RemoveSavedTool_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RemoveSavedToolRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VassagoServer).RemoveSavedTool(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Vassago_RemoveSavedTool_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VassagoServer).RemoveSavedTool(ctx, req.(*RemoveSavedToolRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Vassago_SyncChanges_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SyncChangesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VassagoServer).SyncChanges(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Vassago_SyncChanges_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VassagoServer).SyncChanges(ctx, req.(*SyncChangesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Vassago_AddTask_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddTaskRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VassagoServer).AddTask(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Vassago_AddTask_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VassagoServer).AddTask(ctx, req.(*AddTaskRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Vassago_GetTask_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTaskRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VassagoServer).GetTask(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Vassago_GetTask_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VassagoServer).GetTask(ctx, req.(*GetTaskRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Vassago_ClaimTask_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ClaimTaskRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VassagoServer).ClaimTask(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Vassago_ClaimTask_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VassagoServer).ClaimTask(ctx, req.(*ClaimTaskRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Vassago_CompleteTask_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CompleteTaskRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VassagoServer).CompleteTask(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Vassago_CompleteTask_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VassagoServer).CompleteTask(ctx, req.(*CompleteTaskRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Vassago_FailTask_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FailTaskRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VassagoServer).FailTask(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Vassago_FailTask_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VassagoServer).FailTask(ctx, req.(*FailTaskRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Vassago_FindReadyTasks_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FindReadyTasksRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VassagoServer).FindReadyTasks(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Vassago_FindReadyTasks_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VassagoServer).FindReadyTasks(ctx, req.(*FindReadyTasksRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Vassago_ListTasksByStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListTasksByStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VassagoServer).ListTasksByStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Vassago_ListTasksByStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VassagoServer).ListTasksByStatus(ctx, req.(*ListTasksByStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Vassago_ResetTimedOutTasks_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ResetTimedOutTasksRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VassagoServer).ResetTimedOutTasks(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Vassago_ResetTimedOutTasks_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VassagoServer).ResetTimedOutTasks(ctx, req.(*ResetTimedOutTasksRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Vassago_DeleteTask_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteTaskRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VassagoServer).DeleteTask(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Vassago_DeleteTask_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VassagoServer).DeleteTask(ctx, req.(*DeleteTaskRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Vassago_ServiceDesc is the grpc.ServiceDesc for Vassago service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Vassago_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "vassago.Vassago",
	HandlerType: (*VassagoServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Ping",
			Handler:    _Vassago_Ping_Handler,
		},
		{
			MethodName: "AddMemory",
			Handler:    _Vassago_AddMemory_Handler,
		},
		{
			MethodName: "GetMemory",
			Handler:    _Vassago_GetMemory_Handler,
		},
		{
			MethodName: "UpdateMemory",
			Handler:    _Vassago_UpdateMemory_Handler,
		},
		{
			MethodName: "RemoveMemory",
			Handler:    _Vassago_RemoveMemory_Handler,
		},
		{
			MethodName: "ListMemories",
			Handler:    _Vassago_ListMemories_Handler,
		},
		{
			MethodName: "Search",
			Handler:    _Vassago_Search_Handler,
		},
		{
			MethodName: "SearchSessions",
			Handler:    _Vassago_SearchSessions_Handler,
		},
		{
			MethodName: "ListSessions",
			Handler:    _Vassago_ListSessions_Handler,
		},
		{
			MethodName: "GetHotBlock",
			Handler:    _Vassago_GetHotBlock_Handler,
		},
		{
			MethodName: "CreateSession",
			Handler:    _Vassago_CreateSession_Handler,
		},
		{
			MethodName: "AddMessages",
			Handler:    _Vassago_AddMessages_Handler,
		},
		{
			MethodName: "EndSession",
			Handler:    _Vassago_EndSession_Handler,
		},
		{
			MethodName: "GetSession",
			Handler:    _Vassago_GetSession_Handler,
		},
		{
			MethodName: "Consolidate",
			Handler:    _Vassago_Consolidate_Handler,
		},
		{
			MethodName: "GetConsolidationCandidates",
			Handler:    _Vassago_GetConsolidationCandidates_Handler,
		},
		{
			MethodName: "RegisterAgent",
			Handler:    _Vassago_RegisterAgent_Handler,
		},
		{
			MethodName: "Heartbeat",
			Handler:    _Vassago_Heartbeat_Handler,
		},
		{
			MethodName: "AddTodo",
			Handler:    _Vassago_AddTodo_Handler,
		},
		{
			MethodName: "CompleteTodo",
			Handler:    _Vassago_CompleteTodo_Handler,
		},
		{
			MethodName: "RemoveTodo",
			Handler:    _Vassago_RemoveTodo_Handler,
		},
		{
			MethodName: "AddSkill",
			Handler:    _Vassago_AddSkill_Handler,
		},
		{
			MethodName: "GetSkill",
			Handler:    _Vassago_GetSkill_Handler,
		},
		{
			MethodName: "ListSkills",
			Handler:    _Vassago_ListSkills_Handler,
		},
		{
			MethodName: "RemoveSkill",
			Handler:    _Vassago_RemoveSkill_Handler,
		},
		{
			MethodName: "SearchSkills",
			Handler:    _Vassago_SearchSkills_Handler,
		},
		{
			MethodName: "AddSavedTool",
			Handler:    _Vassago_AddSavedTool_Handler,
		},
		{
			MethodName: "GetSavedTool",
			Handler:    _Vassago_GetSavedTool_Handler,
		},
		{
			MethodName: "ListSavedTools",
			Handler:    _Vassago_ListSavedTools_Handler,
		},
		{
			MethodName: "SearchSavedTools",
			Handler:    _Vassago_SearchSavedTools_Handler,
		},
		{
			MethodName: "UpdateSavedTool",
			Handler:    _Vassago_UpdateSavedTool_Handler,
		},
		{
			MethodName: "RemoveSavedTool",
			Handler:    _Vassago_RemoveSavedTool_Handler,
		},
		{
			MethodName: "SyncChanges",
			Handler:    _Vassago_SyncChanges_Handler,
		},
		{
			MethodName: "AddTask",
			Handler:    _Vassago_AddTask_Handler,
		},
		{
			MethodName: "GetTask",
			Handler:    _Vassago_GetTask_Handler,
		},
		{
			MethodName: "ClaimTask",
			Handler:    _Vassago_ClaimTask_Handler,
		},
		{
			MethodName: "CompleteTask",
			Handler:    _Vassago_CompleteTask_Handler,
		},
		{
			MethodName: "FailTask",
			Handler:    _Vassago_FailTask_Handler,
		},
		{
			MethodName: "FindReadyTasks",
			Handler:    _Vassago_FindReadyTasks_Handler,
		},
		{
			MethodName: "ListTasksByStatus",
			Handler:    _Vassago_ListTasksByStatus_Handler,
		},
		{
			MethodName: "ResetTimedOutTasks",
			Handler:    _Vassago_ResetTimedOutTasks_Handler,
		},
		{
			MethodName: "DeleteTask",
			Handler:    _Vassago_DeleteTask_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Subscribe",
			Handler:       _Vassago_Subscribe_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "ChatStream",
			Handler:       _Vassago_ChatStream_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "ListTodos",
			Handler:       _Vassago_ListTodos_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "proto/vassago.proto",
}

const (
	AgentChat_ChatStream_FullMethodName = "/vassago.AgentChat/ChatStream"
	AgentChat_Ping_FullMethodName       = "/vassago.AgentChat/Ping"
)

// AgentChatClient is the client API for AgentChat service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// AgentChat is a lightweight gRPC service exposed by the agent binary
// for interactive conversations over gRPC. It only implements chat
// and health, not the full Vassago daemon service.
type AgentChatClient interface {
	ChatStream(ctx context.Context, in *ChatRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ChatEvent], error)
	Ping(ctx context.Context, in *HealthCheckRequest, opts ...grpc.CallOption) (*HealthCheckResponse, error)
}

type agentChatClient struct {
	cc grpc.ClientConnInterface
}

func NewAgentChatClient(cc grpc.ClientConnInterface) AgentChatClient {
	return &agentChatClient{cc}
}

func (c *agentChatClient) ChatStream(ctx context.Context, in *ChatRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ChatEvent], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &AgentChat_ServiceDesc.Streams[0], AgentChat_ChatStream_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[ChatRequest, ChatEvent]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type AgentChat_ChatStreamClient = grpc.ServerStreamingClient[ChatEvent]

func (c *agentChatClient) Ping(ctx context.Context, in *HealthCheckRequest, opts ...grpc.CallOption) (*HealthCheckResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HealthCheckResponse)
	err := c.cc.Invoke(ctx, AgentChat_Ping_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AgentChatServer is the server API for AgentChat service.
// All implementations must embed UnimplementedAgentChatServer
// for forward compatibility.
//
// AgentChat is a lightweight gRPC service exposed by the agent binary
// for interactive conversations over gRPC. It only implements chat
// and health, not the full Vassago daemon service.
type AgentChatServer interface {
	ChatStream(*ChatRequest, grpc.ServerStreamingServer[ChatEvent]) error
	Ping(context.Context, *HealthCheckRequest) (*HealthCheckResponse, error)
	mustEmbedUnimplementedAgentChatServer()
}

// UnimplementedAgentChatServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAgentChatServer struct{}

func (UnimplementedAgentChatServer) ChatStream(*ChatRequest, grpc.ServerStreamingServer[ChatEvent]) error {
	return status.Error(codes.Unimplemented, "method ChatStream not implemented")
}
func (UnimplementedAgentChatServer) Ping(context.Context, *HealthCheckRequest) (*HealthCheckResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Ping not implemented")
}
func (UnimplementedAgentChatServer) mustEmbedUnimplementedAgentChatServer() {}
func (UnimplementedAgentChatServer) testEmbeddedByValue()                   {}

// UnsafeAgentChatServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AgentChatServer will
// result in compilation errors.
type UnsafeAgentChatServer interface {
	mustEmbedUnimplementedAgentChatServer()
}

func RegisterAgentChatServer(s grpc.ServiceRegistrar, srv AgentChatServer) {
	// If the following call panics, it indicates UnimplementedAgentChatServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AgentChat_ServiceDesc, srv)
}

func _AgentChat_ChatStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ChatRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(AgentChatServer).ChatStream(m, &grpc.GenericServerStream[ChatRequest, ChatEvent]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type AgentChat_ChatStreamServer = grpc.ServerStreamingServer[ChatEvent]

func _AgentChat_Ping_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HealthCheckRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentChatServer).Ping(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentChat_Ping_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentChatServer).Ping(ctx, req.(*HealthCheckRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// AgentChat_ServiceDesc is the grpc.ServiceDesc for AgentChat service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AgentChat_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "vassago.AgentChat",
	HandlerType: (*AgentChatServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Ping",
			Handler:    _AgentChat_Ping_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "ChatStream",
			Handler:       _AgentChat_ChatStream_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "proto/vassago.proto",
}

const (
	CronService_CreateCronJob_FullMethodName = "/vassago.CronService/CreateCronJob"
	CronService_ListCronJobs_FullMethodName  = "/vassago.CronService/ListCronJobs"
	CronService_UpdateCronJob_FullMethodName = "/vassago.CronService/UpdateCronJob"
	CronService_DeleteCronJob_FullMethodName = "/vassago.CronService/DeleteCronJob"
)

// CronServiceClient is the client API for CronService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// CronService manages scheduled recurring jobs that trigger agent actions.
// Jobs are stored durably in the daemon and fire at their scheduled intervals.
type CronServiceClient interface {
	// Create a new cron job
	CreateCronJob(ctx context.Context, in *CreateCronJobRequest, opts ...grpc.CallOption) (*CronJob, error)
	// List cron jobs, optionally filtered by agent
	ListCronJobs(ctx context.Context, in *ListCronJobsRequest, opts ...grpc.CallOption) (*CronJobList, error)
	// Update an existing cron job (partial update — only set fields are changed)
	UpdateCronJob(ctx context.Context, in *UpdateCronJobRequest, opts ...grpc.CallOption) (*CronJob, error)
	// Delete a cron job
	DeleteCronJob(ctx context.Context, in *DeleteCronJobRequest, opts ...grpc.CallOption) (*Empty, error)
}

type cronServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewCronServiceClient(cc grpc.ClientConnInterface) CronServiceClient {
	return &cronServiceClient{cc}
}

func (c *cronServiceClient) CreateCronJob(ctx context.Context, in *CreateCronJobRequest, opts ...grpc.CallOption) (*CronJob, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CronJob)
	err := c.cc.Invoke(ctx, CronService_CreateCronJob_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cronServiceClient) ListCronJobs(ctx context.Context, in *ListCronJobsRequest, opts ...grpc.CallOption) (*CronJobList, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CronJobList)
	err := c.cc.Invoke(ctx, CronService_ListCronJobs_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cronServiceClient) UpdateCronJob(ctx context.Context, in *UpdateCronJobRequest, opts ...grpc.CallOption) (*CronJob, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CronJob)
	err := c.cc.Invoke(ctx, CronService_UpdateCronJob_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cronServiceClient) DeleteCronJob(ctx context.Context, in *DeleteCronJobRequest, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, CronService_DeleteCronJob_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CronServiceServer is the server API for CronService service.
// All implementations must embed UnimplementedCronServiceServer
// for forward compatibility.
//
// CronService manages scheduled recurring jobs that trigger agent actions.
// Jobs are stored durably in the daemon and fire at their scheduled intervals.
type CronServiceServer interface {
	// Create a new cron job
	CreateCronJob(context.Context, *CreateCronJobRequest) (*CronJob, error)
	// List cron jobs, optionally filtered by agent
	ListCronJobs(context.Context, *ListCronJobsRequest) (*CronJobList, error)
	// Update an existing cron job (partial update — only set fields are changed)
	UpdateCronJob(context.Context, *UpdateCronJobRequest) (*CronJob, error)
	// Delete a cron job
	DeleteCronJob(context.Context, *DeleteCronJobRequest) (*Empty, error)
	mustEmbedUnimplementedCronServiceServer()
}

// UnimplementedCronServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedCronServiceServer struct{}

func (UnimplementedCronServiceServer) CreateCronJob(context.Context, *CreateCronJobRequest) (*CronJob, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateCronJob not implemented")
}
func (UnimplementedCronServiceServer) ListCronJobs(context.Context, *ListCronJobsRequest) (*CronJobList, error) {
	return nil, status.Error(codes.Unimplemented, "method ListCronJobs not implemented")
}
func (UnimplementedCronServiceServer) UpdateCronJob(context.Context, *UpdateCronJobRequest) (*CronJob, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateCronJob not implemented")
}
func (UnimplementedCronServiceServer) DeleteCronJob(context.Context, *DeleteCronJobRequest) (*Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteCronJob not implemented")
}
func (UnimplementedCronServiceServer) mustEmbedUnimplementedCronServiceServer() {}
func (UnimplementedCronServiceServer) testEmbeddedByValue()                     {}

// UnsafeCronServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CronServiceServer will
// result in compilation errors.
type UnsafeCronServiceServer interface {
	mustEmbedUnimplementedCronServiceServer()
}

func RegisterCronServiceServer(s grpc.ServiceRegistrar, srv CronServiceServer) {
	// If the following call panics, it indicates UnimplementedCronServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&CronService_ServiceDesc, srv)
}

func _CronService_CreateCronJob_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateCronJobRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CronServiceServer).CreateCronJob(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CronService_CreateCronJob_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CronServiceServer).CreateCronJob(ctx, req.(*CreateCronJobRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CronService_ListCronJobs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListCronJobsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CronServiceServer).ListCronJobs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CronService_ListCronJobs_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CronServiceServer).ListCronJobs(ctx, req.(*ListCronJobsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CronService_UpdateCronJob_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateCronJobRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CronServiceServer).UpdateCronJob(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CronService_UpdateCronJob_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CronServiceServer).UpdateCronJob(ctx, req.(*UpdateCronJobRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CronService_DeleteCronJob_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteCronJobRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CronServiceServer).DeleteCronJob(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CronService_DeleteCronJob_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CronServiceServer).DeleteCronJob(ctx, req.(*DeleteCronJobRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// CronService_ServiceDesc is the grpc.ServiceDesc for CronService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var CronService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "vassago.CronService",
	HandlerType: (*CronServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateCronJob",
			Handler:    _CronService_CreateCronJob_Handler,
		},
		{
			MethodName: "ListCronJobs",
			Handler:    _CronService_ListCronJobs_Handler,
		},
		{
			MethodName: "UpdateCronJob",
			Handler:    _CronService_UpdateCronJob_Handler,
		},
		{
			MethodName: "DeleteCronJob",
			Handler:    _CronService_DeleteCronJob_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/vassago.proto",
}
